### ISSUE TITLE
デフォルトの画像

### ISSUE THREAD

**Issue by yuji** [movabletype/mt-theme-rimo#10]
MTのロゴが下付きなのが気になるような、ならないような。
<img width="464" alt="2017-06-27 08 58 36" src="https://user-images.githubusercontent.com/70859/27565081-e3bde50a-5b16-11e7-9562-ce95c68dc7b2.png">

**Comment by wtnbtkfm** [comment]
画像を修正し、かつスタイルも調整しました。
アイコンが少し小さくなっていますが、これで常に上下左右センターにアイコンが表示されます。

**Comment by yuji** [comment]
Okay!
