### ISSUE TITLE
themeのauthor

### ISSUE THREAD

**Issue by yuji** [movabletype/mt-theme-rimo#11]
Author: -

なので Simple Corporate と同じく

author_link: 'http://www.movabletype.org/'
author_name: 'Six Apart, Ltd.'

**Comment by terukick** [comment]
最後にまとめてやる

**Comment by wtnbtkfm** [comment]
@yuji 
theme.yamlのauthor周りを設定しました。

**Comment by yuji** [comment]
Okay!
