### ISSUE TITLE
tophmail-240.png っているの？

### ISSUE THREAD

**Issue by yuji** [movabletype/mt-theme-rimo#13]
このまま使われることを想定している画像なのだろうか・・・。
もし、使ってないなら削除。使ってるなら・・・うーん。画像の中にSAのロゴとか入ってるしダメだろうｗ

**Comment by wtnbtkfm** [comment]
こちらSAブログで使われているものらしく、.netのテーマでも特に使われていないようだったので削除しました。

**Comment by yuji** [comment]
消えてるのを確認。
