### ISSUE TITLE
ブログのテーマとして RIMO が選択できない

### ISSUE THREAD

**Issue by yuji** [movabletype/mt-theme-rimo#14]
class: website なのはあえて？

**Comment by wtnbtkfm** [comment]
ウェブサイトにテーマをあてて開発し始めてしまっているため、書き出すとwebsiteになってしまうんですよね。
一通り構築が完了してtheme.yamlを修正する時にblogに変更します！

**Comment by wtnbtkfm** [comment]
@yuji 
classをblogに変更しました。

**Comment by yuji** [comment]
Okay!
