### ISSUE TITLE
Theme の名前と概要

### ISSUE THREAD

**Issue by yuji** [movabletype/mt-theme-rimo#16]
RIMO のテーマだとなんかキャラテーマっぽい。他のテーマ同様 RIMO でいいのではないか？
あと、テーマの概要がないのでなんか欲しい。

**Comment by terukick** [comment]
「Rimo は弊社のオウンドメディア Six Aprt ブログ で実際に利用しているテーマを汎用的に利用できるようにしたものです。」

**Comment by makisawa** [comment]
概要ですが、下記でお願いできますか。

Rimo は、実際のオウンドメディア運用のノウハウを活かして作られた、企業のオウンドメディアサイト構築に最適なテーマです。SNSボタンの配置や、関連記事への導線などにも配慮されているため、簡単なカスタマイズでスピーディーに運用を開始できます。

あと、テーマ名は小文字混じりの「Rimo」でお願いします。ロゴマークはRIMOですが、文字で表記するときはRimoのようなので、統一します。

**Comment by wtnbtkfm** [comment]
@yuji 
テーマの名前と概要を修正しました。
上記の澤さんから指定のあった内容にしてあります。

**Comment by yuji** [comment]
label: RIMO                                                                                                                                           
name: RIMO                                                                                                                                            
description: "RIMO テーマは、簡単にメディアサイトを作れるテーマです。"                                                                                

となってるよ

* RIMO はすべて Rimo に統一
    * テンプレやページの中も含み
* description は https://github.com/movabletype/mt-theme-rimo/issues/16#issuecomment-312993421 で。

**Comment by wtnbtkfm** [comment]
@yuji 
コミット漏れていたようです！申し訳ありません！
こちらで再度ご確認お願いします。

**Comment by yuji** [comment]
Okay!
