### ISSUE TITLE
システムテンプレートの中身

### ISSUE THREAD

**Issue by yuji** [movabletype/mt-theme-rimo#17]
https://github.com/movabletype/mt-theme-SimpleCorporate/issues/38

ここでも同じことがあったんだけど、Rimoでも同じことが起きてるよ。
中身空っぽにしないか？

**Comment by wtnbtkfm** [comment]
失念しておりました、、
システムテンプレートは全て中身を空にしました！

**Comment by yuji** [comment]
Okay!
