### ISSUE TITLE
メンバーアイコンのTitle

### ISSUE THREAD

**Issue by yuji** [movabletype/mt-theme-rimo#4]
アイコンにカーソルを合わせたとき何も表示されないので、Title にも alt と同じ内容を入れたほうがよくない？

**Comment by wtnbtkfm** [comment]
メンバーアイコンにtitleを設定しました。
ご確認お願いします。

**Comment by yuji** [comment]
@wtnbtkfm 
ん？どこに入ったのかしら？

サイドバーのメンバーアイコン、記事のメンバーアイコン（２つ）、Author アーカイブのアイコン、どこにも入ってないような

**Comment by wtnbtkfm** [comment]
記事一覧のメンバーアイコン（小さく表示されるもの）のaタグにだけ設定していました。
残りのアイコンにも設定するので少々お待ちください！

**Comment by wtnbtkfm** [comment]
メンバーアイコン全てにtitleを設定しました。
再度ご確認お願いします。

**Comment by yuji** [comment]
@wtnbtkfm 
Aタグについてるけど、IMGタグの方がよくない？
記事無いとリンク作られないし。

**Comment by wtnbtkfm** [comment]
@yuji 
titleはaタグにつけるものだと勝手に思い込んでいたのですが、調べてみたところ、
altはimgタグ専用
titleはどの要素にも自由につけられる
が正解だったようです。
imgに付け直しましたのでご確認お願いします！

**Comment by yuji** [comment]
Okay!
