### ISSUE TITLE
サイトの Description が"副題"で サイトの紹介文は 固定文字なのは違和感

### ISSUE THREAD

**Issue by yuji** [movabletype/mt-theme-rimo#5]
があるのだけれども。
サイトのCFでサブタイトル
Descriptionが自動で紹介文に入る。という方がナチュラルじゃないか？

**Comment by yuji** [comment]
meta description, og:description にも使われることを考えると サイトの description が紹介文というのもちょっと違うのか？サイトのCFで紹介文のほうがいいのかしら

**Comment by terukick** [comment]
テーマの使いやすさを考えると、サイドメニューの「このサイトについて」もウェブサイトの説明を出力するようにしておいて、もっと長い文章とか違うのを入れたいという人はそこを良きにかえてねって感じですかね？

**Comment by terukick** [comment]
この部分はもともとの.netのテーマを踏襲しているとのこと。

**Comment by yuji** [comment]
このサイトについてのページを表示はいいかも。
それ自体、サイト上にあって良い気もするし。
デフォルトだとページもカテゴリも何もないから、テーマインストールでページ用意して、ページの概要をサイドバーでは表示するとか？

**Comment by terukick** [comment]
それでいきましょう

**Comment by wtnbtkfm** [comment]
テーマインストールで「このサイトについて」というウェブページが追加され、そのタイトルと概要がサイドバーに出力されるようにしました。
ご確認お願いします。

**Comment by yuji** [comment]
* <mt:PageExcerpt remove_html="1"> になってるから概要のHTMLが除去されてしまい、一本調子のテキストしか表示されない。

**Comment by wtnbtkfm** [comment]
@yuji 
良かれと思ってremove_htmlしていたのですが、確かに汎用性にかけると思いますので削除しました。

**Comment by yuji** [comment]
ごめん、もういっこ気がついた。

ページのタグが「about」よりはシークレットタグの方がよくない？「@ABOUT」みたいな。

**Comment by wtnbtkfm** [comment]
@yuji 
theme.yamlにページのタグとして@aboutを設定して、次に管理画面にアクセスすると
Error reading /home/wimwim/www/mt/themes/rimo/theme.yaml: YAML::Tiny found illegal characters in plain scalar: '@about' 
こんなエラーが出てしまうんですよね。
theme.yaml内に@とかって使えなかったりしますか？

**Comment by yuji** [comment]
いや、Rainier とか他のは使ってるよ。"@ABOUT" と括る必要あるかな

**Comment by wtnbtkfm** [comment]
おお、申し訳ありません。
修正しましたので再度ご確認お願いします。

**Comment by yuji** [comment]
Okay!
