### ISSUE TITLE
Google カスタム検索のデフォルト値

### ISSUE THREAD

**Issue by yuji** [movabletype/mt-theme-rimo#6]
001983609055171639828:kku7yjsvwhi

これはどっかのID？

**Comment by wtnbtkfm** [comment]
@yuji 
これはMovableType.netのテーマにもともと入っていたもので、「活用ブログ」専用のIDですね。
確かにこのままではちょっと微妙ですかね、、、
デフォルトはsixapart.jpのものにしておいてIDを消したら検索窓ごと消える、という感じで対応しようと思うのですが、いかがでしょうか？

**Comment by yuji** [comment]
うーん。sa.jpをカスタム検索で指定されても何かな。と思うのでデフォルトは空で、カラのときは非表示でいんじゃないかしら。

**Comment by wtnbtkfm** [comment]
承知しました！ではその線で修正します。
ユーザーにはパッと見てこの機能の存在がわからなくなると思うので、ドキュメントに追記した方が良さそうですね。
修正してプッシュしたら再度ご報告します。

**Comment by wtnbtkfm** [comment]
デフォルトは空で非表示、IDが入力されたら表示、に修正しました。
ご確認お願いします。

**Comment by yuji** [comment]
Okay!

Google カスタム検索の件はカスタマイズガイドに記述お願いします。
