### ISSUE TITLE
twitterVia の初期値

### ISSUE THREAD

**Issue by yuji** [movabletype/mt-theme-rimo#7]
Simple Corporate では 最終的には空にしたけど、こっちは movabletype が入っているのは仕様？

**Comment by terukick** [comment]
.netではデフォルトがこうなっている。

**Comment by terukick** [comment]
Simple Corporateに寄せた方がよいので、空にします。

**Comment by wtnbtkfm** [comment]
デフォルトは空、に修正しました。
ご確認お願いします。

**Comment by yuji** [comment]
Okay!
