### ISSUE TITLE
表示件数を2にすると無限スクロールしない

### ISSUE THREAD

**Issue by yuji** [movabletype/mt-theme-rimo#8]
まあ、そんなもんだよね。とは思うけどｗ
念のため報告

**Comment by wtnbtkfm** [comment]
@yuji 
今は「共通変数」モジュールで設定する表示件数以下になっていると無限スクロールしなくなってしますますね。
これなんですが、例えば管理画面上の表示件数を共通変数の表示件数の変数に設定できれば2にしても無限スクロールできると思うのですが、管理画面の表示件数を取得できるmtタグってあったりしますか？

**Comment by yuji** [comment]
記事3件あったけどスクロールエリアよりサイドバーが長いからスクロールのイベントが発火してないんじゃないかしら。

ちなみにタグはないと思う

**Comment by wtnbtkfm** [comment]
おお、、そういうことですか。。。
であれば、今のjsを使っている限りちょっと難しそうですね。
とりあえず今の所このままでも大丈夫でしょうか？
将来的にはなんとかしたいと思います！

**Comment by yuji** [comment]
あい。だいじょうぶ。

設定上の注意としてサイドバーより短いときは無限スクロールしないから設定した件数より表示されることが絶対にないので注意。というかんじか。

まあ、10件前後を推奨します。てきな。

**Comment by wtnbtkfm** [comment]
ありがとうございます！
後ほどまとめてgithub上のドキュメントを更新しますー

**Comment by wtnbtkfm** [comment]
@yuji 
wikiに無限スクロールに関する注釈を追加しました。
https://github.com/movabletype/mt-theme-rimo/wiki/specification

**Comment by yuji** [comment]
Thanks!
