### ISSUE TITLE
この記事の筆者に壊れた画像

### ISSUE THREAD

**Issue by yuji** [movabletype/mt-theme-rimo#9]
<img width="891" alt="2017-06-27 08 55 38" src="https://user-images.githubusercontent.com/70859/27565036-7afd9e3e-5b16-11e7-8eb6-d9e5365a296e.png">
/images/prof_own.svg

**Comment by wtnbtkfm** [comment]
こちら調べてみたところ、テーマに書き出す際に/imagesフォルダを丸っと含まれるようにしてあるんですが、/imagesの中に入っているsvgファイルが全て消えてしまっているようです。
これってmtの仕様だったりしますか？

**Comment by yuji** [comment]
@wtnbtkfm 

https://www.movabletype.jp/documentation/appendices/config-directives/themestaticfileextensions.html

これだね。
エクスポートする MT で

ThemeStaticFileExtensions jpg jpeg gif png js css ico flv swf html otf ttf svg

的な。

**Comment by wtnbtkfm** [comment]
おお、、申し訳有りません。不勉強でした。
svg一式アップしましたのでこちらで再度ご確認お願いします！

**Comment by yuji** [comment]
ThemeStaticFileExtensions
これ、テーマの適用時にも使ってるな・・・。
再適用しても入らないからおかしいなと思ったら、適用時にも見てるよ・・・。
ドキュメント嘘つきだよ・・・。おかしいよ・・・。

**Comment by wtnbtkfm** [comment]
お、、そうなんですね。ではsvgは使わないでpngとかに置き換えた方が良さそうですかね？
ちなみに先ほど開発中のmtに「ThemeStaticFileExtensions」を設定したんですが、
設定してからテーマをエクスポートしようとするとmtというかperlがエラーを吐いてしまったため
svgだけ手動でマージしました。僕の環境だけかもしれませんが念のためご報告します！

**Comment by yuji** [comment]
@wtnbtkfm 

ボクのところ、適用時にエラー吐くね・・・。svgファイルのコピーに失敗しているようだが・・。
もし、pngでも良いならそっちにしよう

**Comment by wtnbtkfm** [comment]
こちらと同じような感じですね。
それではsvgをpngに置き換えますね。
svg結構使っていますので少々お時間ください！

**Comment by wtnbtkfm** [comment]
svgを全てpngに置き換えました。
こちらで再度ご確認お願いします。

**Comment by yuji** [comment]
確認しました

**Comment by yuji** [comment]
ここもアイコンのTitleに “<mt:AuthorDisplayName escape="html">”の記事一覧 的なのが欲しいかも？
ほかも全体的に見直してもらったほうがよいかも。

**Comment by wtnbtkfm** [comment]
@yuji 
一通り見直して、小さいアイコンが表示されるところには全てtitleが設定されるようにしました。

**Comment by yuji** [comment]
Okay!
